[tool.black]
line-length = 100
target-version = ["py313"]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["month1", "month2", "qa_lab"]

[tool.mypy]
python_version = "3.13"
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
warn_unused_ignores = true
ignore_missing_imports = true
explicit_package_bases = true

exclude = '''
(
  (^|/)(tests?|test_.*\.py$)     # any tests
| (^|/).*week3_full_suite/.*     # your week 3 integration tests
| (^|/).*practice/.*             # practice folders
| (^|/)conftest\.py$             # any conftest.py
)
'''

[[tool.mypy.overrides]]
module = [
  "month2.week1.*",
  "month2.week2.*",
  "month2.week3.*",
  "month1.week2.*",
  "month1.week3.*",
]
ignore_errors = true

