[tool.black]
line-length = 100
target-version = ["py313"]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B"]

ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["month1", "month2", "qa_lab"]
